version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: sajuna-blog-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: sajuna_blog
      MYSQL_USER: ${MYSQL_USER:-blog_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-blog_password}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: sajuna-blog-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    container_name: sajuna-blog-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=blog_user
      - DB_PASSWORD=${MYSQL_PASSWORD:-blog_password}
      - DB_NAME=sajuna_blog
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GIN_TRUSTED_PROXIES=172.18.0.0/16  # 信任Docker网络内的代理
    depends_on:
      - mysql
      - redis
    volumes:
      - ./backend:/app
      - /app/vendor

  frontend:
    build: ./frontend
    container_name: sajuna-blog-frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mysql_data:
  redis_data:



