server:
  port: "8080"
  mode: "debug"

database:
  dsn: "root:password@tcp(localhost:3306)/sajuna_blog?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

jwt:
  secret: "sajuna-blog-secret-key-change-in-production"
  expire: 24



